# NumPy Basics:

In [2]:
%matplotlib inline

In [3]:
import numpy as np
import pandas as pd
from numpy.random import randn

# The Numpy ndarray: a multidimensional array object
# ndarray: 一种多维数组对象

In [4]:
data = randn(2, 3)

In [5]:
data

array([[ 1.62966253, -0.11569874, -0.78201697],
       [-0.43864439,  1.07524631,  0.08589742]])

## creating ndarrays

In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim

2

In [9]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [10]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
np.arange(1, 15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.empty((2, 3, 4))
# 认为 np.empty会返回全0数组的想法是不安全的。多数情况下，它返回一些未初始化的垃圾值。

array([[[  2.69749882e-316,   6.51907723e-316,   2.69218465e-316,
           6.52007168e-316],
        [  2.71704287e-316,   6.52011318e-316,   2.69218465e-316,
           2.69749882e-316],
        [  6.52243727e-316,   2.69218465e-316,   6.51438835e-316,
           2.69750159e-316]],

       [[  2.71704287e-316,   6.52241830e-316,   2.69218465e-316,
           3.97518934e-316],
        [  2.69750159e-316,   6.52243727e-316,   2.69218465e-316,
           6.51766855e-316],
        [  2.71704287e-316,   6.52244043e-316,   2.69218465e-316,
           6.10257277e-316]]])

In [ ]:
np.eye(3)

In [16]:
np.eye((2))

array([[ 1.,  0.],
       [ 0.,  1.]])

## Data Types for ndarrays

In [18]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)


In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [22]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [23]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [24]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [25]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)